name: hire_me
description: Reach me hub.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.1
  cloud_firestore: ^2.2.1
  firebase_storage: ^8.0.3
  get: ^4.1.4
  url_launcher: ^6.0.4
  material_design_icons_flutter: ^4.0.5955
  google_fonts: ^2.0.0
  file_picker: ^3.0.2+2
  intl: ^0.17.0
  universal_io: ^2.0.4
  carousel_slider: ^4.0.0
  expandable: ^5.0.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway-Bold.ttf
        weight: 700
      - asset: assets/fonts/Raleway-Black.ttf
        weight: 900
  - family: RobotoCondensed
    fonts:
      - asset: assets/fonts/RobotoCondensed-Regular.ttf
      - asset: assets/fonts/RobotoCondensed-Bold.ttf
        weight: 700
      - asset: assets/fonts/RobotoCondensed-Light.ttf
        weight: 300
      - asset: assets/fonts/RobotoCondensed-Italic.ttf
        style: italic
  - family: Lemonada
    fonts: 
      - asset: assets/fonts/Lemonada-Bold.ttf
      - asset: assets/fonts/Lemonada-Medium.ttf
      - asset: assets/fonts/Lemonada-Regular.ttf
  - family: Kufam
    fonts: 
      - asset: assets/fonts/Kufam-Bold.ttf
      - asset: assets/fonts/Kufam-Medium.ttf
      - asset: assets/fonts/Kufam-Regular.ttf
        

 